basic:
	xelatex basic-math.tex
	open basic-math.pdf

qthreats:
	xelatex quthreats.tex
	open quthreats.pdf

outline:
	xelatex outline.tex
	open outline.pdf

all: basic qthreats outline
	echo "Done!"
	
clean:
	@rm -f *.aux *.log *.snm *.out *.toc *.nav *.vrb

